#include "softloaf_trichrome/color_management.hpp"

#include <lcms2.h>

#include <memory>
#include <string>

namespace softloaf::trichrome::color {
namespace {

struct ProfileDeleter {
    void operator()(cmsHPROFILE profile) const {
        if (profile) cmsCloseProfile(profile);
    }
};

struct CurveDeleter {
    void operator()(cmsToneCurve* curve) const {
        if (curve) cmsFreeToneCurve(curve);
    }
};

using ProfilePtr = std::unique_ptr<void, ProfileDeleter>;
using CurvePtr = std::unique_ptr<cmsToneCurve, CurveDeleter>;

cmsCIExyY ToCmsWhite(Xy white) {
    return {white.x, white.y, 1.0};
}

cmsCIExyY ToCmsPrimary(Xy primary) {
    return {primary.x, primary.y, 1.0};
}

CurvePtr BuildToneCurve(const RgbColorSpace& space) {
    if (space.transfer == TransferCurve::kSrgb) {
        const double params[] = {
            2.4,
            1.0 / 1.055,
            0.055 / 1.055,
            0.04045,
            1.0 / 12.92,
            0.0,
            0.0,
        };
        return CurvePtr(cmsBuildParametricToneCurve(nullptr, 4, params));
    }
    return CurvePtr(cmsBuildGamma(nullptr, space.gamma));
}

void WriteAsciiTag(cmsHPROFILE profile, cmsTagSignature tag, std::string_view text) {
    cmsMLU* mlu = cmsMLUalloc(nullptr, 1);
    if (!mlu) return;
    const std::string copy(text);
    cmsMLUsetASCII(mlu, "en", "US", copy.c_str());
    cmsWriteTag(profile, tag, mlu);
    cmsMLUfree(mlu);
}

}  // namespace

std::vector<unsigned char> CreateIccProfile(const RgbColorSpace& space) {
    cmsCIExyY white = ToCmsWhite(space.white);
    cmsCIExyYTRIPLE primaries = {
        ToCmsPrimary(space.primaries.red),
        ToCmsPrimary(space.primaries.green),
        ToCmsPrimary(space.primaries.blue),
    };
    CurvePtr curve = BuildToneCurve(space);
    if (!curve) return {};
    cmsToneCurve* curves[3] = {curve.get(), curve.get(), curve.get()};

    ProfilePtr profile(cmsCreateRGBProfile(&white, &primaries, curves));
    if (!profile) return {};

    cmsSetProfileVersion(profile.get(), 4.3);
    WriteAsciiTag(profile.get(), cmsSigProfileDescriptionTag, space.label);
    WriteAsciiTag(profile.get(), cmsSigCopyrightTag,
                  "Generated by SoftLoaf Trichrome from colour-science RGB colourspace constants.");

    cmsUInt32Number bytes = 0;
    if (!cmsSaveProfileToMem(profile.get(), nullptr, &bytes) || bytes == 0) return {};

    std::vector<unsigned char> out(bytes);
    if (!cmsSaveProfileToMem(profile.get(), out.data(), &bytes)) return {};
    out.resize(bytes);
    return out;
}

}  // namespace softloaf::trichrome::color
